export const PROJECT_TYPES = {
  novel: {
    label: 'Novel',
    icon: '📚',
    description: 'Full-length prose fiction',
    structure: { level1: 'Act', level2: 'Chapter', level3: 'Scene' },
    planningTab: 'PLANNING',
    writingTab: 'WRITING',
    sections: ['outline','characters','familytree','factions','locations','lore','ideas','schedule','timeline','worldhistory','map'],
  },
  novella: {
    label: 'Novella',
    icon: '📖',
    description: 'Short to medium-length prose fiction',
    structure: { level1: 'Part', level2: 'Chapter', level3: 'Scene' },
    planningTab: 'PLANNING',
    writingTab: 'WRITING',
    sections: ['outline','characters','factions','locations','lore','ideas','schedule','timeline','map'],
  },
  short_story: {
    label: 'Short Story',
    icon: '📄',
    description: 'Brief prose fiction',
    structure: { level1: 'Part', level2: 'Section', level3: 'Scene' },
    planningTab: 'PLANNING',
    writingTab: 'WRITING',
    sections: ['outline','characters','locations','lore','ideas','schedule'],
  },
  play: {
    label: 'Play',
    icon: '🎭',
    description: 'Stage play or theatrical script',
    structure: { level1: 'Act', level2: 'Scene', level3: 'Beat' },
    planningTab: 'PLANNING',
    writingTab: 'SCRIPT',
    sections: ['outline','characters','familytree','locations','lore','ideas','schedule'],
  },
  screenplay: {
    label: 'Screenplay',
    icon: '🎬',
    description: 'Feature film or short film script',
    structure: { level1: 'Act', level2: 'Sequence', level3: 'Scene' },
    planningTab: 'PLANNING',
    writingTab: 'SCRIPT',
    sections: ['outline','characters','factions','locations','lore','ideas','schedule','timeline'],
  },
  tv_show: {
    label: 'TV Series',
    icon: '📺',
    description: 'Multi-episode television series',
    structure: { level1: 'Season', level2: 'Episode', level3: 'Act' },
    planningTab: 'PLANNING',
    writingTab: 'EPISODES',
    sections: ['outline','characters','familytree','factions','locations','lore','ideas','schedule','timeline','worldhistory'],
  },
  dnd_campaign: {
    label: 'D&D Campaign',
    icon: '⚔️',
    description: 'Dungeons & Dragons adventure',
    structure: { level1: 'Story Arc', level2: 'Session', level3: 'Encounter' },
    planningTab: 'WORLDBUILDING',
    writingTab: 'SESSIONS',
    sections: ['outline','characters','factions','locations','lore','ideas','schedule','timeline','worldhistory','map'],
  },
  tabletop_rpg: {
    label: 'TTRPG Campaign',
    icon: '🎲',
    description: 'Tabletop roleplaying campaign',
    structure: { level1: 'Story Arc', level2: 'Session', level3: 'Encounter' },
    planningTab: 'WORLDBUILDING',
    writingTab: 'SESSIONS',
    sections: ['outline','characters','factions','locations','lore','ideas','schedule','timeline','worldhistory','map'],
  },
  comic: {
    label: 'Comic / Graphic Novel',
    icon: '💬',
    description: 'Sequential art narrative',
    structure: { level1: 'Volume', level2: 'Issue', level3: 'Page' },
    planningTab: 'PLANNING',
    writingTab: 'PAGES',
    sections: ['outline','characters','factions','locations','lore','ideas','schedule','timeline','map'],
  },
  video_game: {
    label: 'Video Game',
    icon: '🎮',
    description: 'Interactive narrative or game world',
    structure: { level1: 'Act', level2: 'Chapter', level3: 'Scene' },
    planningTab: 'WORLDBUILDING',
    writingTab: 'LEVELS',
    sections: ['outline','characters','factions','locations','lore','ideas','schedule','timeline','worldhistory','map'],
  },
}

export const getProjectType = (type) => PROJECT_TYPES[type] ?? PROJECT_TYPES.novel

export const DEFAULT_TYPE = 'novel'
